version: '2.1'
services:
  firego:
    hostname: firego
    image: tmprimitivo/firego
    container_name: firego
    ports:
      - 5000:5000
    networks:
      - app-network

  socketio:
    # build: ./socketio/
    image: docker.pkg.github.com/applinh/goreact-chatapp/chatapp-client:latest
    container_name: socketio
    ports:
      - 8000:8000
    networks:
      - app-network

  client:
    # build: ./client/
    image: docker.pkg.github.com/applinh/goreact-chatapp/chatapp-socketio:latest
    ports:
      - 80:80
    container_name: client
    networks:
      - app-network

networks:
  app-network:
